api:

  image:
    repository: my-app-api
    tag: latest
    pullPolicy: Never


  nodeSelector: {}
  ports:
  - name: "backend-port"
    port: 5009
    targetPort: 5009
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP

frontend:
  args:
  - npm
  - run
  - dev
  - --
  - --host
  image:
    repository: my-app-ui
    tag: latest
    pullPolicy: Never
  nodeSelector: {}
  ports:
  - name: "5173"
    port: 5173
    targetPort: 5173
  replicas: 1
  strategy:
    type: Recreate
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
kubernetesClusterDomain: cluster.local
pvc:
  claim0:
    storageRequest: 100Mi
  claim1:
    storageRequest: 100Mi
